Add support for rocket_contrib's uuids
mateuszkj/okapi pull request #2
Opened 2021-04-22 11:46 UTC by raffomania

This should fix https://github.com/GREsau/okapi/issues/38. I'm creating the PR here as we're using your branch in our application.

It should be noted that `FromForm` still does not work with rocket_contrib uuids, because they do not implement the `JsonSchema` trait. This should probably be fixed in schemars by adding support for rocket_contrib.

2021-05-12 21:44 UTC, ralpha reviewed
I just looked at this, but have not reviewed it in depth or tested it.
But some initial suggestions.

2021-05-12 21:44 UTC, ralpha commented on rocket-okapi/Cargo.toml
> +features = ["json", "uuid"]
Create a new feature for the `uuid` so it is not required by projects that don't want this.
This is also needed because of `optional = true` at line 18
```suggestion
features = ["json"]

[features]
default = []

# Enable both the `uuid` crate and `uuid` feature in `rocket_contrib`
uuid = ["uuid", "rocket_contrib/uuid"]
```

More info can be found here: https://doc.rust-lang.org/cargo/reference/features.html#optional-dependencies
And here: https://doc.rust-lang.org/cargo/reference/features.html#dependency-features

2021-06-06 22:57 UTC, mpajkowski commented
Hello,

Thanks for contributing and for review @raffomania, @ralpha !

Sorry I didn't took any action sooner, I didn't notice this PR. @raffomania , are you still interested in working on this PR?

Best regards,
Marcin

2021-06-06 23:01 UTC, mpajkowski requested changes

2021-06-06 23:01 UTC, mpajkowski commented on rocket-okapi/src/request/from_form_param_impls.rs
> +            extensions: Default::default(),
```suggestion
            extensions: okapi::Map::default(),
```

Please use explicit `default`

2021-06-06 23:01 UTC, mpajkowski commented on rocket-okapi/src/request/from_param_impls.rs
> +            extensions: Default::default(),
```suggestion
            extensions: okapi::Map::default(),
```

Please use explicit `default`

2021-06-07 11:31 UTC, raffomania commented
Awesome, thanks for the review! I will update the PR within the week.

2021-06-10 01:17 UTC, mateuszkj commented on examples/uuid/Cargo.toml
> +rocket = { git = "https://github.com/SergioBenitez/Rocket.git", branch = "master", default-features = false }
Please update to rocket 0.5.0-rc.1 and rebase

2021-06-13 06:04 UTC, svenstaro commented
This should be a closed and the rebased and updated PR should be made directly against the now-active-again upstream over at  https://github.com/GREsau/okapi

2021-06-13 06:07 UTC, mateuszkj commented
@svenstaro you're right. @raffomania I'm closing this PR here.

2021-06-13 06:07 UTC, closed without merging

2021-06-13 10:32 UTC, raffomania commented
I will open a PR upstream, thanks for the reviews. This might even be supported out of the box, with rocket including `uuid` now.